import { useEffect, useMemo, useState } from 'react'
import { ArrowUpRight, BookOpen, Bot, BrainCircuit, Check, ChevronRight, Download, FilePlus2, Grid2X2, Library, Lightbulb, Network, NotebookPen, Plus, Search, Sparkles, Star, Tags, TrendingUp, X } from 'lucide-react'
import './App.css'

type View = 'home' | 'library' | 'cards' | 'map' | 'assistant'
type Book = { id:string; title:string; author:string; category:string; cover:string; color:string; progress:number; cards:number; rating:number }
type Card = { id:string; title:string; bookId:string; category:string; excerpt:string; insight:string; application:string; tags:string[]; importance:number; updated:string }

const INITIAL_BOOKS: Book[] = [
  {id:'naval',title:'纳瓦尔宝典',author:'埃里克·乔根森',category:'自我成长',cover:'N',color:'#a6b6f3',progress:100,cards:18,rating:5},
  {id:'positioning',title:'定位',author:'艾·里斯 / 杰克·特劳特',category:'商业',cover:'定',color:'#e8a08f',progress:100,cards:24,rating:5},
  {id:'principles',title:'原则',author:'瑞·达利欧',category:'管理',cover:'原',color:'#b4d7c3',progress:100,cards:16,rating:4},
  {id:'thinking',title:'思考，快与慢',author:'丹尼尔·卡尼曼',category:'心理学',cover:'思',color:'#eacb89',progress:76,cards:12,rating:4},
  {id:'innovator',title:'创新者的窘境',author:'克莱顿·克里斯坦森',category:'商业',cover:'创',color:'#9bc9d5',progress:100,cards:15,rating:5},
  {id:'meditations',title:'沉思录',author:'马可·奥勒留',category:'哲学',cover:'沉',color:'#c4acd6',progress:63,cards:9,rating:4},
]
const INITIAL_CARDS: Card[] = [
  {id:'compound',title:'复利效应',bookId:'naval',category:'财富创造',excerpt:'财富不是你劳动时赚到的钱，而是睡觉时仍在为你工作的资产。',insight:'真正值得投入的是那些能长期积累、可复制且不依赖单次努力的事情。',application:'建立内容、产品与关系等可持续增长的资产，而非只追求一次性结果。',tags:['长期主义','财富','杠杆'],importance:5,updated:'今天'},
  {id:'specific',title:'特定知识',bookId:'naval',category:'财富创造',excerpt:'找到你独特的知识组合：它往往不是课堂里最容易教授的部分。',insight:'优势来自兴趣、天赋、经历和判断力的交集，而非和所有人竞争同一种标准技能。',application:'盘点自己反复被请教、做起来有能量的领域，持续公开表达。',tags:['能力','职业','差异化'],importance:5,updated:'昨天'},
  {id:'mindshare',title:'用户心智',bookId:'positioning',category:'品牌定位',excerpt:'营销的战场不在产品中，而在潜在顾客的心智中。',insight:'品牌不是自我定义，而是用户在某个需求出现时首先想起你的理由。',application:'为产品选择一个清晰、聚焦、可验证的品类词，并在每次沟通中重复它。',tags:['品牌','营销','定位'],importance:5,updated:'8月17日'},
  {id:'believability',title:'可信度加权决策',bookId:'principles',category:'决策系统',excerpt:'不要只听声音最大的观点，应让更可信的人拥有更大的决策权重。',insight:'高质量决策来自观点多样性与可追溯的判断记录，而不是权威压制。',application:'在项目复盘中记录预测、依据和结果，为领域专家逐步建立可信度档案。',tags:['决策','管理','复盘'],importance:4,updated:'8月16日'},
  {id:'disruption',title:'破坏式创新',bookId:'innovator',category:'创新战略',excerpt:'优秀企业失败，常常不是因为管理不善，而是因为太善于服务现有客户。',insight:'新市场早期的利润率和性能都不漂亮，因此需要独立资源与耐心来培育。',application:'为探索性产品设定不同于成熟业务的指标，避免被短期 ROI 过早扼杀。',tags:['创业','战略','创新'],importance:5,updated:'8月12日'},
  {id:'system',title:'系统一与系统二',bookId:'thinking',category:'认知偏差',excerpt:'快速直觉带来效率，也会让我们在不知不觉中跳过检验。',insight:'重要判断应故意创造慢下来的流程，以对抗第一反应的过度自信。',application:'在高风险决策中引入反证问题：什么事实会让我承认自己错了？',tags:['思维','决策','偏差'],importance:4,updated:'8月10日'},
]
const covers = ['navy','coral','mint','gold','sky','purple']
const STORE = 'knowledge-garden-v1'

export default function App() {
  const [view,setView] = useState<View>('home'), [books,setBooks] = useState<Book[]>(INITIAL_BOOKS), [cards,setCards] = useState<Card[]>(INITIAL_CARDS)
  const [query,setQuery] = useState(''), [activeBook,setActiveBook] = useState('all'), [selected,setSelected] = useState<Card | null>(null)
  const [addBook,setAddBook] = useState(false), [addCard,setAddCard] = useState(false), [toast,setToast] = useState('')
  const [question,setQuestion] = useState(''), [answer,setAnswer] = useState('')
  useEffect(()=>{ try { const saved=JSON.parse(localStorage.getItem(STORE)||''); if(saved.books) setBooks(saved.books); if(saved.cards) setCards(saved.cards) } catch {} },[])
  useEffect(()=>localStorage.setItem(STORE,JSON.stringify({books,cards})),[books,cards])
  const bookFor=(id:string)=>books.find(b=>b.id===id)
  const foundBooks=useMemo(()=>books.filter(b=>(activeBook==='all'||b.id===activeBook)&&(`${b.title} ${b.author} ${b.category}`).toLowerCase().includes(query.toLowerCase())),[books,query,activeBook])
  const foundCards=useMemo(()=>cards.filter(c=>(activeBook==='all'||c.bookId===activeBook)&&(`${c.title} ${c.insight} ${c.tags.join(' ')} ${bookFor(c.bookId)?.title||''}`).toLowerCase().includes(query.toLowerCase())),[cards,query,activeBook])
  const notify=(text:string)=>{ setToast(text); setTimeout(()=>setToast(''),2200) }
  const saveBook=(title:string,author:string,category:string)=>{ const b={id:`b-${Date.now()}`,title,author:author||'未知作者',category,cover:title[0],color:['#a6b6f3','#e8a08f','#b4d7c3','#eacb89'][books.length%4],progress:0,cards:0,rating:0}; setBooks(x=>[b,...x]); setActiveBook(b.id); setAddBook(false); setView('library'); notify('新书已加入你的书架') }
  const saveCard=(title:string,bookId:string,insight:string)=>{ const c={id:`c-${Date.now()}`,title,bookId,category:'我的思考',excerpt:insight,insight,application:'把这个观点放进真实项目中检验，并在之后记录反馈。',tags:['我的笔记'],importance:4,updated:'刚刚'}; setCards(x=>[c,...x]); setBooks(x=>x.map(b=>b.id===bookId?{...b,cards:b.cards+1}:b));setSelected(c);setAddCard(false);setView('cards');notify('知识卡片已保存') }
  const download=()=>{ const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({exportedAt:new Date().toISOString(),books,cards},null,2)],{type:'application/json'}));a.download='my-knowledge-garden.json';a.click();notify('知识库备份已下载') }
  const ask=(input=question)=>{ if(!input.trim()) return; const terms=input; const related=cards.filter(c=>terms.includes('品牌')?c.tags.includes('品牌')||c.tags.includes('营销'):terms.includes('创业')?c.tags.includes('创业')||c.tags.includes('战略'):terms.includes('决策')?c.tags.includes('决策'):true).slice(0,3); const source=[...new Set(related.map(c=>bookFor(c.bookId)?.title))].join('、'); setAnswer(related.length?`我在你的知识库中找到了 ${related.length} 个相关观点，主要来自《${source}》。\n\n${related.map(c=>`「${c.title}」强调${c.insight}`).join('；')}。\n\n建议：把这些原则应用到一个正在推进的真实项目中，并为结果建立复盘卡片。`:'还没有找到直接相关的卡片。你可以先创建一张卡片，或使用更具体的关键词提问。') }
  const nav:[View,string,typeof Grid2X2][]=[['home','知识大厅',Grid2X2],['library','我的书架',Library],['cards','知识卡片',NotebookPen],['map','知识地图',Network],['assistant','AI 助手',Bot]]
  return <main className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark"><BrainCircuit size={20}/></span><span>知知<b>KNOWLEDGE GARDEN</b></span></div><nav>{nav.map(([id,label,Icon])=><button key={id} className={`nav-item ${view===id?'is-active':''}`} onClick={()=>setView(id)}><Icon size={18}/>{label}</button>)}</nav><hr/><p className="side-label">我的领域</p>{['商业','自我成长','管理','心理学','哲学'].map((name,i)=><button className="area-item" key={name} onClick={()=>{setView('library');setQuery(name)}}><i className={`dot d${i}`}/>{name}<span>{books.filter(b=>b.category===name).length}</span></button>)}<div className="side-bottom"><button className="backup" onClick={download}><Download size={16}/><span><b>你的知识，始终归你</b><small>下载本地备份</small></span></button><div className="profile"><span>Z</span><div><b>我的知识花园</b><small>离线优先 · 已保存</small></div></div></div></aside>
  <section className="main"><header><div className="mobile-brand"><BrainCircuit size={20}/> 知知</div><label className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索书籍、观点或标签…"/><kbd>⌘ K</kbd></label><button className="add" onClick={()=>setAddBook(true)}><Plus size={17}/> 新建</button></header><div className="page">
  {view==='home'&&<Home books={books} cards={cards} open={setSelected} to={setView} add={()=>setAddCard(true)}/>} {view==='library'&&<LibraryPage books={foundBooks} all={books} active={activeBook} choose={setActiveBook} add={()=>setAddBook(true)}/>} {view==='cards'&&<CardsPage cards={foundCards} books={books} open={setSelected} add={()=>setAddCard(true)}/>} {view==='map'&&<MapPage cards={cards} books={books} open={c=>{setSelected(c);setView('cards')}}/>} {view==='assistant'&&<Assistant question={question} answer={answer} setQuestion={setQuestion} ask={ask} total={cards.length}/>}</div></section>
  {selected&&<Drawer card={selected} book={bookFor(selected.bookId)} close={()=>setSelected(null)}/>} {addBook&&<BookModal close={()=>setAddBook(false)} save={saveBook}/>} {addCard&&<CardModal books={books} close={()=>setAddCard(false)} save={saveCard}/>} {toast&&<div className="toast"><Check size={15}/>{toast}</div>}</main>
}
function Title({eyebrow,title,description,action}:{eyebrow:string,title:string,description:string,action?:React.ReactNode}) { return <div className="title"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div>{action}</div> }
function BookTile({book,index}:{book:Book,index:number}) { return <article className="book-tile"><div className={`cover ${covers[index%covers.length]}`} style={{'--c':book.color} as React.CSSProperties}><span>{book.category}</span><strong>{book.title}</strong><small>{book.author}</small><i>{book.cover}</i></div><h3>{book.title}</h3><p>{book.cards} 个知识点 · {book.progress===100?'已读完':`阅读中 ${book.progress}%`}</p></article> }
function Home({books,cards,open,to,add}:{books:Book[],cards:Card[],open:(c:Card)=>void,to:(v:View)=>void,add:()=>void}) { const featured=cards[0];return <><Title eyebrow="WED · 2026.08.19" title="欢迎回到你的知识花园。" description="让阅读沉淀，让思考生长。" action={<button className="outline" onClick={add}><FilePlus2 size={16}/>记录一个想法</button>}/><section className="hero"><article className="review"><div className="spark"><Sparkles size={19}/></div><p className="overline">今日随机回顾</p><h2>{featured.title}</h2><p className="quote">“{featured.excerpt}”</p><div><span>《{books.find(b=>b.id===featured.bookId)?.title}》</span><button onClick={()=>open(featured)}>打开卡片 <ArrowUpRight size={14}/></button></div></article><article className="growth"><div><p className="overline">知识增长</p><h3>本月新增 <b>18</b> 个连接</h3></div><span className="rise"><TrendingUp size={14}/>24%</span><section>{[31,46,38,64,54,83,74].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</section><small>周一　周二　周三　周四　周五　周六　今天</small></article></section><div className="section-title"><div><h2>最近阅读</h2><p>正在生长的知识脉络</p></div><button onClick={()=>to('library')}>查看书架 <ChevronRight size={16}/></button></div><div className="book-row">{books.slice(0,4).map((b,i)=><BookTile book={b} index={i} key={b.id}/>)}</div><section className="insights"><div className="section-title"><div><h2>最近的洞见</h2><p>你写下的可复用思考</p></div><button onClick={()=>to('cards')}>全部卡片 <ChevronRight size={16}/></button></div>{cards.slice(1,4).map(c=><button className="insight" key={c.id} onClick={()=>open(c)}><span><Lightbulb size={16}/></span><div><b>{c.title}</b><p>{c.insight}</p><small>《{books.find(b=>b.id===c.bookId)?.title}》 · {c.updated}</small></div><ChevronRight size={17}/></button>)}</section></> }
function LibraryPage({books,all,active,choose,add}:{books:Book[],all:Book[],active:string,choose:(x:string)=>void,add:()=>void}) { return <><Title eyebrow="MY LIBRARY" title="我的书架" description={`已收藏 ${all.length} 本书，沉淀 ${all.reduce((n,b)=>n+b.cards,0)} 个知识点。`} action={<button className="add" onClick={add}><Plus size={16}/>添加书籍</button>}/><div className="filters"><button className={active==='all'?'active':''} onClick={()=>choose('all')}>全部书籍 <span>{all.length}</span></button>{all.slice(0,5).map(b=><button className={active===b.id?'active':''} onClick={()=>choose(b.id)} key={b.id}>{b.title}</button>)}</div>{books.length?<div className="library-grid">{books.map((b,i)=><article className="library-book" key={b.id}><div className={`cover large ${covers[i%covers.length]}`} style={{'--c':b.color} as React.CSSProperties}><span>{b.category}</span><strong>{b.title}</strong><small>{b.author}</small><i>{b.cover}</i></div><div><p className="category">{b.category}</p><h2>{b.title}</h2><p>{b.author}</p><div className="stats"><span><NotebookPen size={14}/>{b.cards} 个知识点</span><span><Star size={14} fill="currentColor"/>{b.rating||'未评分'}</span></div><div className="progress"><i style={{width:`${b.progress}%`}}/><small>{b.progress===100?'已读完':`阅读进度 ${b.progress}%`}</small></div></div></article>)}</div>:<Empty title="没有匹配的书籍" text="换个搜索词，或创建一本新书。" icon={<Search/>}/>}</> }
function CardsPage({cards,books,open,add}:{cards:Card[],books:Book[],open:(x:Card)=>void,add:()=>void}) { return <><Title eyebrow="KNOWLEDGE CARDS" title="知识卡片" description="把摘录变成有来源、有理解、有行动的知识资产。" action={<button className="add" onClick={add}><Plus size={16}/>新建卡片</button>}/>{cards.length?<div className="card-grid">{cards.map((c,i)=><button className={`card tint${i%4}`} key={c.id} onClick={()=>open(c)}><div><span>{c.category}</span><b>{'✦'.repeat(c.importance)}</b></div><h2>{c.title}</h2><blockquote>“{c.excerpt}”</blockquote><p>{c.insight}</p><section>{c.tags.map(t=><i key={t}>#{t}</i>)}</section><footer><BookOpen size={14}/>《{books.find(b=>b.id===c.bookId)?.title}》<ArrowUpRight size={13}/></footer></button>)}</div>:<Empty title="没有找到知识卡片" text="从书中提炼一个可以复用的观点吧。" icon={<Tags/>}/>}</> }
function MapPage({cards,books,open}:{cards:Card[],books:Book[],open:(c:Card)=>void}) { return <><Title eyebrow="KNOWLEDGE GRAPH" title="知识地图" description="每一次连接，都让你的思考变得更完整。" action={<button className="outline"><Network size={16}/>自动发现连接</button>}/><section className="map"><div className="canvas"><div className="map-meta"><Network size={15}/>38 个知识节点</div><svg viewBox="0 0 900 520" preserveAspectRatio="none"><path d="M175 285 C275 135 360 180 430 245 S620 125 760 165"/><path d="M175 285 C280 375 365 395 465 360 S630 340 760 285"/><path d="M430 245 C460 280 470 310 465 360"/><path d="M430 245 C570 245 650 255 760 285"/></svg>{cards.slice(0,6).map((c,i)=><button className={`node n${i}`} key={c.id} onClick={()=>open(c)}><span>{i===0?<Sparkles size={14}/>:<BookOpen size={14}/>}</span><b>{c.title}</b><small>《{books.find(x=>x.id===c.bookId)?.title}》</small></button>)}</div><aside><p className="overline">主题聚类</p><h2>商业与长期主义</h2><p>这组知识围绕“创造长期价值”形成了最密集的连接。</p><div><span><i/>财富创造 <b>8</b></span><span><i/>品牌定位 <b>6</b></span><span><i/>创新战略 <b>5</b></span></div><button>查看关联笔记 <ChevronRight size={16}/></button></aside></section></> }
function Assistant({question,answer,setQuestion,ask,total}:{question:string,answer:string,setQuestion:(x:string)=>void,ask:(input?:string)=>void,total:number}) { const prompts=['总结我的创业方法论','我读过哪些品牌建设的方法？','帮我找关于长期主义的观点'];return <><Title eyebrow="PRIVATE KNOWLEDGE ASSISTANT" title="问问你的知识库。" description={`基于 ${total} 张知识卡片，为你的思考提供可追溯的回答。`}/><section className="assistant"><div className="intro"><span><Bot size={27}/></span><h2>你的私人知识助手</h2><p>它只在当前浏览器中搜索你的卡片，并标明观点来源。</p><div>{prompts.map(x=><button key={x} onClick={()=>{setQuestion(x);ask(x)}}><Sparkles size={13}/>{x}</button>)}</div></div>{answer&&<article className="answer"><b><Bot size={15}/>知知的回答</b>{answer.split('\n\n').map((p,i)=><p key={i}>{p}</p>)}<small>回答基于你的知识卡片生成</small></article>}<div className="ask"><textarea rows={2} value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ask()}}} placeholder="例如：总结我关于创业的核心方法论…"/><button onClick={()=>ask()}><ArrowUpRight size={18}/></button><small>Enter 发送 · 数据仅存储在当前浏览器</small></div></section></> }
function Drawer({card,book,close}:{card:Card,book?:Book,close:()=>void}) { return <div className="overlay" onMouseDown={close}><aside className="drawer" onMouseDown={e=>e.stopPropagation()}><div><span>{card.category}</span><button onClick={close}><X size={18}/></button></div><h2>{card.title}</h2><p className="source"><BookOpen size={15}/>来源 · 《{book?.title}》</p><section><label>原文摘录</label><blockquote>“{card.excerpt}”</blockquote></section><section><label>我的理解</label><p>{card.insight}</p></section><section className="application"><label>可以如何应用</label><p>{card.application}</p></section><div className="tags">{card.tags.map(t=><i key={t}>#{t}</i>)}</div><footer>更新于 {card.updated}<button className="outline"><NotebookPen size={15}/>编辑卡片</button></footer></aside></div> }
function BookModal({close,save}:{close:()=>void,save:(title:string,author:string,category:string)=>void}) { const [title,setTitle]=useState(''),[author,setAuthor]=useState(''),[category,setCategory]=useState('商业');return <div className="overlay modal-wrap" onMouseDown={close}><form className="modal" onMouseDown={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();if(title.trim())save(title.trim(),author.trim(),category)}}><div className="modal-head"><div><p className="eyebrow">NEW BOOK</p><h2>加入一本新书</h2></div><button type="button" onClick={close}><X size={18}/></button></div><label>书名<input autoFocus required value={title} onChange={e=>setTitle(e.target.value)} placeholder="例如：从 0 到 1"/></label><label>作者<input value={author} onChange={e=>setAuthor(e.target.value)} placeholder="作者姓名"/></label><label>领域<select value={category} onChange={e=>setCategory(e.target.value)}>{['商业','心理学','哲学','历史','自我成长','科技'].map(x=><option key={x}>{x}</option>)}</select></label><div className="actions"><button type="button" className="outline" onClick={close}>取消</button><button className="add"><Plus size={16}/>创建书籍</button></div></form></div> }
function CardModal({books,close,save}:{books:Book[],close:()=>void,save:(title:string,book:string,insight:string)=>void}) { const [title,setTitle]=useState(''),[book,setBook]=useState(books[0]?.id||''),[insight,setInsight]=useState('');return <div className="overlay modal-wrap" onMouseDown={close}><form className="modal wide" onMouseDown={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();if(title.trim()&&insight.trim())save(title.trim(),book,insight.trim())}}><div className="modal-head"><div><p className="eyebrow">NEW KNOWLEDGE CARD</p><h2>捕捉一个洞见</h2></div><button type="button" onClick={close}><X size={18}/></button></div><label>知识点标题<input autoFocus required value={title} onChange={e=>setTitle(e.target.value)} placeholder="例如：第一性原理"/></label><label>关联书籍<select value={book} onChange={e=>setBook(e.target.value)}>{books.map(b=><option key={b.id} value={b.id}>{b.title}</option>)}</select></label><label>你的理解<textarea rows={5} required value={insight} onChange={e=>setInsight(e.target.value)} placeholder="这个概念对你意味着什么？它可以怎样被应用？"/></label><div className="actions"><button type="button" className="outline" onClick={close}>取消</button><button className="add"><Sparkles size={16}/>保存卡片</button></div></form></div> }
function Empty({title,text,icon}:{title:string,text:string,icon:React.ReactNode}) { return <div className="empty"><span>{icon}</span><h2>{title}</h2><p>{text}</p></div> }


